version: '3.8'

services:
  db:
    image: postgres:13
    hostname: db
    ports:
       - "5432:5432"
    env_file:
      - .env
    networks:
      - streamtodb
    volumes:
      - ./misc/001-init.sql:/docker-entrypoint-initdb.d/init.sql


  srv:
    build: .
    restart: on-failure
    hostname: server
    env_file:
      - .env
    networks:
      - streamtodb
    deploy:
      resources:
        limits:
          memory: 8M
        reservations:
          memory: 6M
    depends_on:
      - db
    volumes:
      - ./ports.json:/ports.json
    entrypoint: ["/main", "ports.json"]

networks:
  streamtodb:
    driver: bridge